# Generated by Django 4.0.6 on 2023-01-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
