# Generated by Django 4.0.6 on 2023-01-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_delete_slider_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=2255)),
                ('total_amount', models.FloatField(max_length=10)),
                ('date_of_purchase', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('sales_man', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=5)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
    ]
