# Generated by Django 4.0.6 on 2023-01-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_of_purchase',
            field=models.DateTimeField(max_length=50),
        ),
    ]
