# Generated by Django 4.0.6 on 2023-01-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_bill_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_of_purchase',
            field=models.DateField(max_length=50),
        ),
    ]
