# Generated by Django 4.0.6 on 2023-01-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_category_sales_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
