# Generated by Django 4.0.6 on 2023-01-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_bill_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
