# Generated by Django 4.0.6 on 2023-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_bill_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='credit_or_not',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
