# Generated by Django 4.0.6 on 2023-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_bill_credit_or_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='credit_or_not',
            field=models.CharField(default='Payed', max_length=50),
        ),
    ]
