# Generated by Django 4.0.6 on 2023-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoice_alter_bill_credit_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_of_purchase',
            field=models.CharField(max_length=100),
        ),
    ]
